src/Langgas/SisdikBundle/Entity/Sekolah.php
<?php

namespace Langgas\SisdikBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Langgas\SisdikBundle\Util\FileSizeFormatter;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Table(name="sekolah")
 * @ORM\Entity(repositoryClass="Langgas\SisdikBundle\Repository\SekolahRepository")
 * @ORM\HasLifecycleCallbacks
 * @ORM\ChangeTrackingPolicy("DEFERRED_EXPLICIT")
 */
class Sekolah
{
    const LOGO_DIR = 'uploads/sekolah/logo/';
    const THUMBNAIL_PREFIX = 'th1-';
    const MEMORY_LIMIT = '256M';
    const PHOTO_THUMB_WIDTH = 80;
    const PHOTO_THUMB_HEIGHT = 80;

    /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     *
     * @var integer
     */
    private $id;

    /**
     * @ORM\Column(name="nama", type="string", length=300, nullable=false)
     *
     * @var string
     */
    private $nama;

    /**
     * @ORM\Column(name="kode", type="string", length=50, nullable=false)
     *
     * @var string
     */
    private $kode;

    /**
     * @ORM\Column(name="alamat", type="string", length=500, nullable=true)
     *
     * @var string
     */
    private $alamat;

    /**
     * @ORM\Column(name="kodepos", type="string", length=10, nullable=true)
     *
     * @var string
     */
    private $kodepos;

    /**
     * @ORM\Column(name="telepon", type="string", length=50, nullable=true)
     *
     * @var string
     */
    private $telepon;

    /**
     * @ORM\Column(name="fax", type="string", length=50, nullable=true)
     *
     * @var string
     */
    private $fax;

    /**
     * @ORM\Column(name="email", type="string", length=100, nullable=false)
     *
     * @var string
     */
    private $email;

    /**
     * @ORM\Column(name="norekening", type="string", length=100, nullable=true)
     *
     * @var string
     */
    private $norekening;

    /**
     * @ORM\Column(name="bank", type="string", length=100, nullable=true)
     *
     * @var string
     */
    private $bank;

    /**
     * @ORM\Column(name="kepsek", type="string", length=400, nullable=false)
     *
     * @var string
     */
    private $kepsek;

    /**
     * @ORM\Column(name="logo", type="string", length=200, nullable=true)
     *
     * @var string
     */
    private $logo;

    /**
     * @ORM\Column(name="logo_disk", type="string", length=200, nullable=true)
     *
     * @var string
     */
    private $logoDisk;

    /**
     * @ORM\Column(name="awal_pembiayaan", type="string", length=5, nullable=false, options={"fixed"=true, "default"="01/07"})
     * @Assert\NotBlank
     * @Assert\Length(min=5, max=5)
     *
     * @var string
     */
    private $awalPembiayaan = '01/07';

    /**
     * @ORM\Column(name="akhir_pembiayaan", type="string", length=5, nullable=false, options={"fixed"=true, "default"="30/06"})
     * @Assert\NotBlank
     * @Assert\Length(min=5, max=5)
     *
     * @var string
     */
    private $akhirPembiayaan = '30/06';

    /**
     * @Assert\File(maxSize="300k")
     *
     * @var UploadedFile
     */
    private $fileUpload;

    /**
     * @var string
     */
    private $fileDiskSebelumnya;

    /**
     * @ORM\Column(name="nomor_urut", type="integer", nullable=true, options={"unsigned"=true})
     *
     * @var integer
     */
    private $nomorUrut;

    /**
     * @ORM\Column(name="atr_no_daftar", type="string", length=200, nullable=true)
     *
     * @var integer
     */
    private $atributNomorDaftar;

    /**
     * @ORM\Column(name="atr_no_trans_biaya_daftar", type="string", length=200, nullable=true)
     *
     * @var integer
     */
    private $atributNomorTransaksiBiayaDaftar;

    /**
     * @ORM\Column(name="atr_no_trans_biaya_sekali", type="string", length=200, nullable=true)
     *
     * @var integer
     */
    private $atributNomorTransaksiBiayaSekali;

    /**
     * @ORM\Column(name="atr_no_trans_biaya_berulang", type="string", length=200, nullable=true)
     *
     * @var integer
     */
    private $atributNomorTransaksiBiayaBerulang;

    /**
     * @ORM\Column(name="atr_no_trans_restitusi", type="string", length=200, nullable=true)
     *
     * @var integer
     */
    private $atributNomorTransaksiRestitusi;

    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $nama
     */
    public function setNama($nama)
    {
        $this->nama = $nama;
    }

    /**
     * @return string
     */
    public function getNama()
    {
        return $this->nama;
    }

    /**
     * @param string $kode
     */
    public function setKode($kode)
    {
        $this->kode = $kode;
    }

    /**
     * @return string
     */
    public function getKode()
    {
        return $this->kode;
    }

    /**
     * @param string $alamat
     */
    public function setAlamat($alamat)
    {
        $this->alamat = $alamat;
    }

    /**
     * @return string
     */
    public function getAlamat()
    {
        return $this->alamat;
    }

    /**
     * @param string $kodepos
     */
    public function setKodepos($kodepos)
    {
        $this->kodepos = $kodepos;
    }

    /**
     * @return string
     */
    public function getKodepos()
    {
        return $this->kodepos;
    }

    /**
     * @param string $telepon
     */
    public function setTelepon($telepon)
    {
        $this->telepon = $telepon;
    }

    /**
     * @return string
     */
    public function getTelepon()
    {
        return $this->telepon;
    }

    /**
     * @param string $fax
     */
    public function setFax($fax)
    {
        $this->fax = $fax;
    }

    /**
     * @return string
     */
    public function getFax()
    {
        return $this->fax;
    }

    /**
     * @param string $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }

    /**
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param string $norekening
     */
    public function setNorekening($norekening)
    {
        $this->norekening = $norekening;
    }

    /**
     * @return string
     */
    public function getNorekening()
    {
        return $this->norekening;
    }

    /**
     * @param string $bank
     */
    public function setBank($bank)
    {
        $this->bank = $bank;
    }

    /**
     * @return string
     */
    public function getBank()
    {
        return $this->bank;
    }

    /**
     * @param string $kepsek
     */
    public function setKepsek($kepsek)
    {
        $this->kepsek = $kepsek;
    }

    /**
     * @return string
     */
    public function getKepsek()
    {
        return $this->kepsek;
    }

    /**
     * @param string $logo
     */
    public function setLogo($logo)
    {
        $this->logo = $logo;
    }

    /**
     * @return string
     */
    public function getLogo()
    {
        return strlen($this->logo) > 20 ? '...'.substr($this->logo, -17) : $this->logo;
    }

    /**
     * @param string $logoDisk
     */
    public function setLogoDisk($logoDisk)
    {
        $this->logoDisk = $logoDisk;
    }

    /**
     * @return string
     */
    public function getLogoDisk()
    {
        return $this->logoDisk;
    }

    /**
     * @param string $awalPembiayaan
     */
    public function setAwalPembiayaan($awalPembiayaan)
    {
        $this->awalPembiayaan = $awalPembiayaan;
    }

    /**
     * @return string
     */
    public function getAwalPembiayaan()
    {
        return $this->awalPembiayaan;
    }

    /**
     * @param string $akhirPembiayaan
     */
    public function setAkhirPembiayaan($akhirPembiayaan)
    {
        $this->akhirPembiayaan = $akhirPembiayaan;
    }

    /**
     * @return string
     */
    public function getAkhirPembiayaan()
    {
        return $this->akhirPembiayaan;
    }

    /**
     * @param integer $nomorUrut
     */
    public function setNomorUrut($nomorUrut)
    {
        $this->nomorUrut = $nomorUrut;
    }

    /**
     * @return integer
     */
    public function getNomorUrut()
    {
        return $this->nomorUrut;
    }

    /**
     * @param UploadedFile $file
     */
    public function setFileUpload(UploadedFile $file)
    {
        $this->fileUpload = $file;
    }

    /**
     * @return UploadedFile
     */
    public function getFileUpload()
    {
        return $this->fileUpload;
    }

    /**
     * @return NULL|string
     */
    public function getWebPathLogoDisk()
    {
        return null === $this->logoDisk ? null : $this->getUploadDir().DIRECTORY_SEPARATOR.$this->logoDisk;
    }

    /**
     * @return NULL|string
     */
    public function getWebPathLogoThumbnailDisk()
    {
        return null === $this->logoDisk ?
            null : $this->getUploadDir().DIRECTORY_SEPARATOR.self::THUMBNAIL_PREFIX.$this->logoDisk
        ;
    }

    /**
     * @return NULL|string
     */
    public function getRelativePathLogoDisk()
    {
        return null === $this->logoDisk ?
            null : $this->getUploadRootDir().DIRECTORY_SEPARATOR.$this->logoDisk
        ;
    }

    /**
     * @return Ambigous NULL|string
     */
    public function getRelativePathLogoDiskSebelumnya()
    {
        return null === $this->fileDiskSebelumnya ?
            null : $this->getUploadRootDir().DIRECTORY_SEPARATOR.$this->fileDiskSebelumnya
        ;
    }

    /**
     * @return Ambigous NULL|string
     */
    public function getRelativePathLogoThumbDiskSebelumnya()
    {
        return null === $this->fileDiskSebelumnya ?
            null : $this->getUploadRootDir().DIRECTORY_SEPARATOR.self::THUMBNAIL_PREFIX.$this->fileDiskSebelumnya
        ;
    }

    /**
     * @param  string $type
     * @return string
     */
    public function getFilesizeLogoDisk($type = 'KB')
    {

src/Langgas/SisdikBundle/Resources/views/layout.html.twig
{% from 'MopaBootstrapBundle::flash.html.twig' import session_flash %}
{% extends '::base.html.twig' %}

{% block stylesheets %}
    {% stylesheets
        '@MopaBootstrapBundle/Resources/public/less/mopabootstrapbundle.less'
        'bundles/langgassisdik/css/jqueryui/themes/smoothness/jquery-ui-1.9.1.custom.min.css'
        '@LanggasSisdikBundle/Resources/public/css/tooltipster/tooltipster.css'
        '@LanggasSisdikBundle/Resources/public/css/tooltipster/themes/tooltipster-light.css'
        'bundles/langgassisdik/css/styles.css'
        '@LanggasSisdikBundle/Resources/public/css/media-queries.css'
        '@LanggasSisdikBundle/Resources/public/css/dropkick.css'
        filter='cssrewrite'
    %}
        <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}
{% endblock %}

{% block additional_resources %}
{% block javascripts_add %}{% endblock javascripts_add %}
{% block stylesheets_add %}{% endblock stylesheets_add %}
{% endblock additional_resources %}

{% block body %}
{% spaceless %}
<style type="text/css">
.network-logo {
    margin: 0 3px;
}
</style>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ path("_index") }}">
                {% image '@LanggasSisdikBundle/Resources/public/images/logo_white_simple.png' %}
                    <img src="{{ asset_url }}" alt="{{ 'alt.logo'|trans }}" border="0" height="23" style="display: inline-block;">
                {% endimage %}
            </a>
        </div>
        <div class="navbar-collapse collapse">
          {{ mopa_bootstrap_menu('mainMenu') }}
        </div>
    </div>
</div>

<div class="container">
    <div>
        <div style="text-align: right">
          <div id="page-header">
          {% if app.user.sekolah is not null %}
              {% if app.user.sekolah.logo != "" %}
                  <a href="{{ path("_index") }}"><img src="{% if proxypass == 1 %}/{{ proxypassname }}{% endif %}/{{ app.user.sekolah.webPathLogoThumbnailDisk }}" alt="{{ 'alt.logo.sekolah'|trans }}" border="0" class="img-polaroid"></a>
                {% else %}
                    {% image '@LanggasSisdikBundle/Resources/public/images/standar_tutwuri.png' %}
                      <a href="{{ path("_index") }}"><img src="{{ asset_url }}" alt="{{ 'alt.logo.sekolah'|trans }}" border="0" height="80" class="img-polaroid"></a>
                    {% endimage %}
                {% endif %}
            {% else  %}
                {% image '@LanggasSisdikBundle/Resources/public/images/standar_tutwuri.png' %}
                  <a href="{{ path("_index") }}"><img src="{{ asset_url }}" alt="{{ 'alt.logo.sekolah'|trans }}" border="0" height="80" class="img-polaroid"></a>
                {% endimage %}
            {% endif %}
                <div id="school-name">{% spaceless %}
                    {% if app.user is not null %}
                        {% if app.user.sekolah is not null %}{{ app.user.sekolah.nama }}{% endif %}
                    {% endif %}
                {% endspaceless %}</div>
            </div>
            <div id="log-info">
                &raquo; {{ app.user.username }}{% if app.user.nomorPonsel != '' %}, {{ app.user.nomorPonsel }}{% endif %}<br />
                <a href="{{ path("fos_user_profile_show") }}">{% trans from "navigations" %}user.myaccount{% endtrans %}</a> |
                <a href="{{ path("logout") }}">{% trans from "navigations" %}user.logout{% endtrans %}</a>
                {% if is_expr_granted("hasRole('ROLE_PREVIOUS_ADMIN')") %} | <a href="{{ path("homepage", {'_switch_user': '_exit'}) }}">Exit</a>{% endif %}
            </div>
        </div>
    </div>

    <div>
        <div>
            {% if breadcrumb is defined %}
            <div>
                {% for items in breadcrumb %}
                    {% if items.label != 'root' %}
                        <a href="{{ items.uri }}">{{ items.label|trans({}, 'navigations') }}</a>
                        {% if not loop.last %} &raquo; {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            <h2 class="page-title">
                {% block page_heading %}Default Heading{% endblock page_heading %}
            </h2>

            {% block flashes %}
            {% if app.session.flashbag.peekAll|length > 0 %}
                {{ session_flash() }}
            {% endif %}
            {% endblock flashes %}

            <div id="block-content">
{% endspaceless %}{% block content %}
                <h2>Sub Heading</h2>
                <p>Bootstrap default content</p>
                {% endblock content %}{% spaceless %}
            </div>
        </div>
    </div>
</div>

<div class="footer container container-fluid">
    <span style="padding: 10px 0;">&copy; {{ "now"|date("Y") }}</span><span style="padding: 0 10px;">&bull;</span>
    {%- image '@LanggasSisdikBundle/Resources/public/images/logo/wpmini-blue.png' -%}
    <a class="network-logo" href="http://blog.sisdik.com" target="_blank" title="Blog"><img src="{{ asset_url }}" style="vertical-align: middle;"></a>
    {%- endimage -%}
    {%- image '@LanggasSisdikBundle/Resources/public/images/logo/uservoice.png' -%}
    <a class="network-logo" href="https://sisdik.uservoice.com" target="_blank" title="User Voice"><img src="{{ asset_url }}" style="vertical-align: middle;"></a>
    {%- endimage -%}
    {%- image '@LanggasSisdikBundle/Resources/public/images/logo/facebook.png' -%}
    <a class="network-logo" href="http://www.facebook.com/pages/Sisdik/295453420654059" target="_blank" title="Fan Page"><img src="{{ asset_url }}" style="vertical-align: middle;"></a>
    {%- endimage -%}
</div>

{% image '@LanggasSisdikBundle/Resources/public/images/ajax-loader.gif' %}<img src="{{ asset_url }}" class="preload-image">{% endimage %}
{% image '@LanggasSisdikBundle/Resources/public/images/ajax-loader-circle.gif' %}<img src="{{ asset_url }}" class="preload-image">{% endimage %}
{% image '@LanggasSisdikBundle/Resources/public/images/ajax-loader-circle-blue.gif' %}<img src="{{ asset_url }}" class="preload-image">{% endimage %}
{% image '@LanggasSisdikBundle/Resources/public/images/ajax-loader-circle-red.gif' %}<img src="{{ asset_url }}" class="preload-image">{% endimage %}

{% endspaceless %}
{% endblock body %}

{% block javascripts_bottom %}

<!--[if lt IE 9]>
{% javascripts
    '@LanggasSisdikBundle/Resources/public/js/libraries/css3-mediaqueries.js'
    '@LanggasSisdikBundle/Resources/public/js/libraries/html5.js'
%}
<script type="text/javascript" src="{{ asset_url }}"></script>
{% endjavascripts %}
<![endif]-->

{% javascripts
    '@LanggasSisdikBundle/Resources/public/js/libraries/jquery-1.8.3.min.js'
    '@LanggasSisdikBundle/Resources/public/js/libraries/jquery-ui-1.9.1.custom.min.js'
    '@LanggasSisdikBundle/Resources/public/js/libraries/tooltipster/jquery.tooltipster.min.js'
    '@MopaBootstrapBundle/Resources/public/bootstrap/js/tooltip.js'
    '@MopaBootstrapBundle/Resources/public/bootstrap/js/affix.js'
    '@MopaBootstrapBundle/Resources/public/bootstrap/js/alert.js'
    '@MopaBootstrapBundle/Resources/public/bootstrap/js/button.js'
    '@MopaBootstrapBundle/Resources/public/bootstrap/js/carousel.js'
    '@MopaBootstrapBundle/Resources/public/bootstrap/js/collapse.js'
    '@MopaBootstrapBundle/Resources/public/bootstrap/js/dropdown.js'
    '@MopaBootstrapBundle/Resources/public/bootstrap/js/modal.js'
    '@MopaBootstrapBundle/Resources/public/bootstrap/js/popover.js'
    '@MopaBootstrapBundle/Resources/public/bootstrap/js/tab.js'
    '@MopaBootstrapBundle/Resources/public/bootstrap/js/transition.js'
    '@MopaBootstrapBundle/Resources/public/js/mopabootstrap-collection.js'
    '@MopaBootstrapBundle/Resources/public/js/mopabootstrap-subnav.js'
    '@LanggasSisdikBundle/Resources/public/js/custom.js'
%}
<script type="text/javascript" src="{{ asset_url }}"></script>
{% endjavascripts %}

{#     '@MopaBootstrapBundle/Resources/public/bootstrap/js/scrollspy.js'#}

{#     '@LanggasSisdikBundle/Resources/public/js/libraries/bootstrap-transition.js'#}
{#     '@LanggasSisdikBundle/Resources/public/js/libraries/bootstrap-dropdown.js'#}
{#     '@LanggasSisdikBundle/Resources/public/js/libraries/bootstrap-tab.js'#}
{#     '@LanggasSisdikBundle/Resources/public/js/libraries/bootstrap-collapse.js'#}
{#     '@LanggasSisdikBundle/Resources/public/js/libraries/bootstrap-tooltip.js'#}
{#     '@LanggasSisdikBundle/Resources/public/js/libraries/bootstrap-popover.js'#}
{#     '@LanggasSisdikBundle/Resources/public/js/libraries/mopabootstrap-collection.js'#}

{#     '@LanggasSisdikBundle/Resources/public/js/libraries/bootstrap.min.js'#}
{#     '@LanggasSisdikBundle/Resources/public/js/libraries/bootstrap-scrollspy.js'#}
{#     '@LanggasSisdikBundle/Resources/public/js/libraries/bootstrap-carousel.js'#}
{#     '@LanggasSisdikBundle/Resources/public/js/libraries/bootstrap-typeahead.js'#}
{#     '@LanggasSisdikBundle/Resources/public/js/libraries/bootstrap-transition.js'#}
{#     '@LanggasSisdikBundle/Resources/public/js/libraries/bootstrap-modal.js'#}
{#     '@LanggasSisdikBundle/Resources/public/js/libraries/bootstrap-alert.js'#}
{#     '@LanggasSisdikBundle/Resources/public/js/libraries/bootstrap-button.js'#}

<script language="javascript" type="text/javascript">
$(document).ready(function() {
    var resetButton = $(":reset");
    resetButton.each(function() {
        $(this).attr("title", "{{ 'tip.reset.hasil.pencarian'|trans }}");
    });
});
</script>
{% endblock javascripts_bottom %}

{% block javascripts_custom %}{% endblock javascripts_custom %}

{% block lastresources %}{% endblock %}

src/Langgas/SisdikBundle/Resources/views/navbar.html.twig
{% block navbar %}
<div class="navbar{{ (navbar.hasOption('inverse') and  navbar.getOption('inverse')) ? ' navbar-inverse' : '' }}{{ (navbar.hasOption('fixedTop') and  navbar.getOption('fixedTop')) ? ' navbar-fixed-top' : '' }}{{ (navbar.hasOption('staticTop') and  navbar.getOption('staticTop')) ? ' navbar-static-top' : '' }}">
    <div class="navbar-inner">
        <div class="container{{ (navbar.hasOption('isFluid') and navbar.getOption('isFluid')) ? '-fluid' : '' }}">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            {% if navbar.hasOption('title') %}{% spaceless %}
            <a class="brand" href="{{ path(navbar.getOption('titleRoute')) }}" style="padding-top: 3px; padding-bottom: 5px;">
            {% image '@LanggasSisdikBundle/Resources/public/images/logo_white_simple.png' %}
            	<img src="{{ asset_url }}" alt="{{ 'alt.logo'|trans }}" border="0" height="23" style="margin-top: 7px; display: inline-block;">
            {% endimage %}
            </a>
            {% endspaceless %}{% endif %}
            <div class="nav-collapse">
                {{ navbar.hasMenu('leftmenu') ? knp_menu_render(navbar.getMenu('leftmenu'), {'currentClass': 'active', 'ancestorClass': 'active', 'allow_safe_labels': 'true'}) : '' }}
                {% if navbar.hasFormView('searchform') %}
                    {%- set form_view = navbar.getFormView('searchform') -%}
                    {%- set form_type = navbar.getFormType('searchform') -%}
                    {%- set form_attrs = form_view.vars.attr -%}
                    {% form_theme form_view _self %}
                    <form class="navbar-search pull-{{ form_attrs.pull|default('left') }}" method="{{ form_attrs.method|default('post') }}" action="{{ path(navbar.getFormRoute('searchform')) }}">
                    {{ form_widget(form_view) }}
                    </form>
                {% endif %}
                {{ navbar.hasMenu('rightmenu') ? knp_menu_render(navbar.getMenu('rightmenu'), {'currentClass': 'active', 'ancestorClass': 'active', 'allow_safe_labels': 'true'}) : '' }}
            </div>

        </div>
    </div>
</div>
{% endblock %}

{% block form_widget %}
{{ block('field_rows') }}
{% endblock %}

{% block field_row %}
{{ form_widget(form) }}
{% endblock field_row %}