src/Langgas/SisdikBundle/Entity/Tingkat.php
<?php

namespace Langgas\SisdikBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="tingkat")
 * @ORM\Entity
 */
class Tingkat
{
    /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     *
     * @var integer
     */
    private $id;

    /**
     * @ORM\Column(name="kode", type="string", length=45, nullable=false)
     *
     * @var string
     */
    private $kode;

    /**
     * @ORM\Column(name="nama", type="string", length=50, nullable=true)
     *
     * @var string
     */
    private $nama;

    /**
     * @ORM\Column(name="urutan", type="smallint", nullable=true)
     *
     * @var integer
     */
    private $urutan;

    /**
     * @ORM\ManyToOne(targetEntity="Sekolah")
     * @ORM\JoinColumns({
     *     @ORM\JoinColumn(name="sekolah_id", referencedColumnName="id", nullable=false)
     * })
     *
     * @var Sekolah
     */
    private $sekolah;

    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $kode
     */
    public function setKode($kode)
    {
        $this->kode = $kode;
    }

    /**
     * @return string
     */
    public function getKode()
    {
        return $this->kode;
    }

    /**
     * @param string $nama
     */
    public function setNama($nama)
    {
        $this->nama = $nama;
    }

    /**
     * @return string
     */
    public function getNama()
    {
        return $this->nama;
    }

    /**
     * @param integer $urutan
     */
    public function setUrutan($urutan)
    {
        $this->urutan = $urutan;
    }

    /**
     * @return integer
     */
    public function getUrutan()
    {
        return $this->urutan;
    }

    /**
     * @param Sekolah $sekolah
     */
    public function setSekolah(Sekolah $sekolah = null)
    {
        $this->sekolah = $sekolah;
    }

    /**
     * @return Sekolah
     */
    public function getSekolah()
    {
        return $this->sekolah;
    }

    /**
     * @return string
     */
    public function getOptionLabel()
    {
        return $this->getKode() . ' (' . $this->getNama() . ')';
    }
}

src/Langgas/SisdikBundle/Controller/LayananSmsPeriodikController.php
<?php

namespace Langgas\SisdikBundle\Controller;

use Doctrine\DBAL\DBALException;
use Doctrine\ORM\EntityManager;
use Langgas\SisdikBundle\Entity\JadwalKehadiran;
use Langgas\SisdikBundle\Entity\PilihanLayananSms;
use Langgas\SisdikBundle\Entity\LayananSmsPeriodik;
use Langgas\SisdikBundle\Entity\Sekolah;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use JMS\SecurityExtraBundle\Annotation\PreAuthorize;

/**
 * @Route("/layanan-sms-periodik")
 * @PreAuthorize("hasAnyRole('ROLE_ADMIN')")
 */
class LayananSmsPeriodikController extends Controller
{
    /**
     * @Route("/", name="layanan_smsperiodik")
     * @Method("GET")
     * @Template()
     */
    public function indexAction()
    {
        $sekolah = $this->getSekolah();
        $this->setCurrentMenu();

        /* @var $em EntityManager */
        $em = $this->getDoctrine()->getManager();

        $querybuilder = $em->createQueryBuilder()
            ->select('layananSmsPeriodik')
            ->from('LanggasSisdikBundle:LayananSmsPeriodik', 'layananSmsPeriodik')
            ->leftJoin('layananSmsPeriodik.tingkat', 'tingkat')
            ->where('layananSmsPeriodik.sekolah = :sekolah')
            ->orderBy('tingkat.urutan', 'ASC')
            ->addOrderBy('layananSmsPeriodik.jenisLayanan', 'ASC')
            ->setParameter('sekolah', $sekolah)
        ;

        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate($querybuilder, $this->getRequest()->query->get('page', 1));

        return [
            'pagination' => $pagination,
            'daftarJenisLayanan' => array_merge(
                PilihanLayananSms::getDaftarLayananPeriodik()
            ),
            'daftarPerulangan' => LayananSmsPeriodik::getDaftarPerulangan(),
            'daftarBulan' => LayananSmsPeriodik::getDaftarNamaBulan(),
            'daftarHari' => JadwalKehadiran::getNamaHari(),
        ];
    }

    /**
     * @Route("/new", name="layanan_smsperiodik_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {
        $this->setCurrentMenu();

        $entity = new LayananSmsPeriodik();
        $form = $this->createForm('sisdik_layanansmsperiodik', $entity);

        return [
            'entity' => $entity,
            'form' => $form->createView(),
        ];
    }

    /**
     * @Route("/create", name="layanan_smsperiodik_create")
     * @Method("POST")
     * @Template("LanggasSisdikBundle:LayananSmsPeriodik:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $sekolah = $this->getSekolah();

        $this->setCurrentMenu();

        $entity = new LayananSmsPeriodik();
        $form = $this->createForm('sisdik_layanansmsperiodik', $entity);
        $form->submit($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            try {
                $layanan = $em->getRepository('LanggasSisdikBundle:LayananSmsPeriodik')
                    ->findOneBy([
                        'sekolah' => $sekolah,
                        'jenisLayanan' => $entity->getJenisLayanan(),
                        'tingkat' => $entity->getTingkat(),
                    ])
                ;

                if ($layanan instanceof LayananSmsPeriodik) {
                    throw new DBALException();
                }

                $em->persist($entity);
                $em->flush();

                $this
                    ->get('session')
                    ->getFlashBag()
                    ->add('success', $this->get('translator')->trans('flash.layanan.sms.tersimpan'))
                ;
            } catch (DBALException $e) {
                $message = $this->get('translator')->trans('exception.unik.layanan.sms.periodik');
                throw new DBALException($message);
            }

            return $this->redirect($this->generateUrl('layanan_smsperiodik_show', [
                'id' => $entity->getId(),
            ]));
        }

        return [
            'entity' => $entity,
            'form' => $form->createView(),
        ];
    }

    /**
     * @Route("/{id}", name="layanan_smsperiodik_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id)
    {
        $this->setCurrentMenu();

        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('LanggasSisdikBundle:LayananSmsPeriodik')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Entity LayananSmsPeriodik tak ditemukan.');
        }

        if ($this->get('security.authorization_checker')->isGranted('view', $entity) === false) {
            throw new AccessDeniedException($this->get('translator')->trans('akses.ditolak'));
        }

        $deleteForm = $this->createDeleteForm($id);

        return [
            'entity' => $entity,
            'delete_form' => $deleteForm->createView(),
            'daftarJenisLayanan' => array_merge(
                PilihanLayananSms::getDaftarLayananPeriodik()
            ),
            'daftarPerulangan' => LayananSmsPeriodik::getDaftarPerulangan(),
            'daftarBulan' => LayananSmsPeriodik::getDaftarNamaBulan(),
            'daftarHari' => JadwalKehadiran::getNamaHari(),
        ];
    }

    /**
     * @Route("/{id}/edit", name="layanan_smsperiodik_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id)
    {
        $this->setCurrentMenu();

        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('LanggasSisdikBundle:LayananSmsPeriodik')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Entity LayananSmsPeriodik tak ditemukan.');
        }

        if ($this->get('security.authorization_checker')->isGranted('edit', $entity) === false) {
            throw new AccessDeniedException($this->get('translator')->trans('akses.ditolak'));
        }

        $editForm = $this->createForm('sisdik_layanansmsperiodik', $entity);
        $deleteForm = $this->createDeleteForm($id);

        return [
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ];
    }

    /**
     * @Route("/{id}/update", name="layanan_smsperiodik_update")
     * @Method("POST")
     * @Template("LanggasSisdikBundle:LayananSmsPeriodik:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $sekolah = $this->getSekolah();

        $this->setCurrentMenu();

        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('LanggasSisdikBundle:LayananSmsPeriodik')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Entity LayananSmsPeriodik tak ditemukan.');
        }

        if ($this->get('security.authorization_checker')->isGranted('edit', $entity) === false) {
            throw new AccessDeniedException($this->get('translator')->trans('akses.ditolak'));
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createForm('sisdik_layanansmsperiodik', $entity);
        $editForm->submit($request);

        if ($editForm->isValid()) {
            try {
                $layanan = $em->getRepository('LanggasSisdikBundle:LayananSmsPeriodik')
                    ->findOneBy([
                        'sekolah' => $sekolah,
                        'jenisLayanan' => $entity->getJenisLayanan(),
                        'tingkat' => $entity->getTingkat(),
                    ])
                ;

                if ($layanan instanceof LayananSmsPeriodik && $layanan->getId() != $entity->getId()) {
                    throw new DBALException();
                }

                $em->persist($entity);
                $em->flush();

                $this
                    ->get('session')
                    ->getFlashBag()
                    ->add('success', $this->get('translator')->trans('flash.layanan.sms.terbarui'))
                ;
            } catch (DBALException $e) {
                $message = $this->get('translator')->trans('exception.unik.layanan.sms');
                throw new DBALException($message);
            }

            return $this->redirect($this->generateUrl('layanan_smsperiodik_edit', [
                'id' => $id,
            ]));
        }

        return [
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ];
    }

    /**
     * @Route("/{id}/delete", name="layanan_smsperiodik_delete")
     * @Method("POST")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->submit($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('LanggasSisdikBundle:LayananSmsPeriodik')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Entity LayananSmsPeriodik tak ditemukan.');
            }

            if ($this->get('security.authorization_checker')->isGranted('delete', $entity) === false) {
                throw new AccessDeniedException($this->get('translator')->trans('akses.ditolak'));
            }

            $em->remove($entity);
            $em->flush();

            $this
                ->get('session')
                ->getFlashBag()
                ->add('success', $this->get('translator')->trans('flash.layanan.sms.terhapus'))
            ;
        } else {
            $this
                ->get('session')

src/Langgas/SisdikBundle/Resources/views/LayananSmsPeriodik/edit.html.twig
{% extends 'LanggasSisdikBundle::layout.html.twig' %}

{% block page_heading %}{% trans from "headings" %}mengubah.pengaturan.layanan.sms.periodik{% endtrans %}{% endblock %}

{% block content %}
<form action="{{ path('layanan_smsperiodik_update', {'id': entity.id}) }}" method="post" {{ form_enctype(edit_form) }} class="form-horizontal">
    {{ form_widget(edit_form) }}
    <div class="form-group">
        <div class="col-sm-offset-4 col-sm-8 col-md-offset-4 col-md-7 col-lg-offset-3 col-lg-9">
            <button type="submit" class="btn primary">{{ 'label.submit.update'|trans }}</button>
        </div>
    </div>
</form>

<form id="delete-form" action="{{ path('layanan_smsperiodik_delete', {'id': entity.id}) }}" method="post" class="form-inline pull-right">
    {{ form_widget(delete_form) }}
    <button type="submit" class="btn alternative icon danger remove">{{ 'label.delete'|trans }}</button>
</form>

<ul class="nav nav-pills">
    <li>
        <a href="{{ path('layanan_smsperiodik') }}">{{ 'link.backtolist'|trans }}</a>
    </li>
</ul>
{% endblock content %}

{% block javascripts_custom %}
<script language="javascript" type="text/javascript">
$(document).ready(function() {
    $("#delete-form").submit(function(){
        var confirmtext = "{{ 'confirm.drop.layanan.sms'|trans }}";
        confirmtext = confirmtext.replace(/&#039;/g, "'");
        return confirmDropButton(confirmtext);
    });
});
</script>
{% endblock javascripts_custom %}

src/Langgas/SisdikBundle/Resources/views/LayananSmsPeriodik/index.html.twig
{% extends 'LanggasSisdikBundle::layout.html.twig' %}

{% block page_heading %}{% trans from "headings" %}daftar.pengaturan.layanan.sms.periodik{% endtrans %}{% endblock %}

{% block content %}
<style type="text/css">
.start-icon {
    color: #FF6900;
}
</style>

<ul class="nav nav-pills">
    <li>
        <a href="{{ path('layanan_smsperiodik_new') }}" class="add-link-a">
            <i class="fa fa-plus-square fa-lg fa-fw"></i>{{ 'label.tambah.layanan.sms.periodik'|trans }}
        </a>
    </li>
</ul>

<div class="clearfix"></div>

<table class="table zebra-striped bordered-table" id="no-more-tables">
    <thead>
        <tr>
            <th class="{% if pagination.isSorted('layananSmsPeriodik.jenisLayanan') %}sorted{% endif %}">
                {{ knp_pagination_sortable(pagination, 'label.layanansms.jenis'|trans, 'layananSmsPeriodik.jenisLayanan') }}
            </th>
            <th>{{ 'label.kirim.sms'|trans }}</th>
            <th>{{ 'label.actions'|trans }}</th>
        </tr>
    </thead>
    <tbody>
    {% for data in pagination %}
        <tr>
            <td data-title="{{ 'label.layanansms.jenis'|trans }}">{{ daftarJenisLayanan[data.jenisLayanan]|trans }}</td>
            <td data-title="{{ 'label.kirim.sms'|trans }}">
                {% if data.aktif == 1 %}
                    <i class="fa fa-check fa-lg fa-fw check"></i>
                {% else %}
                    <i class="fa fa-times fa-lg fa-fw uncheck"></i>
                {% endif %}
                <span class="separator">|</span>
                {% if data.tingkat %}
                    {{ data.tingkat.optionLabel }}
                {% else %}
                    ∗
                {% endif %}
                <span class="separator">|</span>
                {{ daftarPerulangan[data.perulangan] }}
                <span class="separator">→</span>
                {% if data.perulangan == 'b-mingguan' %}
                    {% if data.mingguanHariKe %}
                        {{ daftarHari[data.mingguanHariKe]|trans }}
                    {% else %}
                        ×
                    {% endif %}
                {% elseif data.perulangan == 'c-bulanan' or data.perulangan == 'd-triwulan' or data.perulangan == 'e-caturwulan' or data.perulangan == 'f-semester' or data.perulangan == 'g-tahunan' %}
                    {% if data.perulangan == 'd-triwulan' or data.perulangan == 'e-caturwulan' or data.perulangan == 'f-semester' or data.perulangan == 'g-tahunan' %}
                        {% if data.bulanAwal != '' %}
                            <i class="fa fa-play start-icon"></i> {{ daftarBulan[data.bulanAwal]|trans }}
                            <span class="separator">→</span>
                        {% else %}
                            ×
                            <span class="separator">→</span>
                        {% endif %}
                    {% endif %}
                    {% if data.bulananHariKe != '' %}
                        {{ 'tanggal'|trans }} {{ data.bulananHariKe }}
                    {% else %}
                        ×
                    {% endif %}
                {% endif %}
                {% if data.perulangan != 'a-harian' %}
                    <span class="separator">→</span>
                {% endif %}
                {% if data.smsJam != '' %}
                    {{ data.smsJam(false) }}
                {% else %}
                    ×
                {% endif %}
                <span class="separator">|</span>
                {{ data.templatesms.nama }}
            </td>
            <td data-title="{{ 'label.actions'|trans }}" class="row-actions">
                <a href="{{ path('layanan_smsperiodik_show', {'id': data.id}) }}" title="{{ 'tip.detail'|trans }}"><i class="fa fa-arrow-right"></i></a>
                <a href="{{ path('layanan_smsperiodik_edit', {'id': data.id}) }}" title="{{ 'tip.edit'|trans }}"><i class="fa fa-pencil"></i></a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{{ knp_pagination_render(pagination) }}
{% endblock content %}

src/Langgas/SisdikBundle/Resources/views/LayananSmsPeriodik/new.html.twig
{% extends 'LanggasSisdikBundle::layout.html.twig' %}

{% block page_heading %}{% trans from "headings" %}membuat.pengaturan.layanan.sms.periodik{% endtrans %}{% endblock %}

{% block content %}
<form action="{{ path('layanan_smsperiodik_create') }}" method="post" {{ form_enctype(form) }} class="form-horizontal">
    {{ form_widget(form) }}
    <div class="form-group">
        <div class="col-sm-offset-4 col-sm-8 col-md-offset-4 col-md-7 col-lg-offset-3 col-lg-9">
            <button type="submit" class="btn primary">{{ 'label.submit.add'|trans }}</button>
        </div>
    </div>
</form>

<ul class="nav nav-pills">
    <li>
        <a href="{{ path('layanan_smsperiodik') }}">{{ 'link.backtolist'|trans }}</a>
    </li>
</ul>
{% endblock content %}

src/Langgas/SisdikBundle/Resources/views/LayananSmsPeriodik/show.html.twig
{% extends 'LanggasSisdikBundle::layout.html.twig' %}

{% block page_heading %}{% trans from "headings" %}detail.layanan.sms.periodik{% endtrans %}{% endblock %}
{% block content %}
<ul class="nav nav-pills pull-right">
    <li>
        <a href="{{ path('layanan_smsperiodik_new') }}" class="add-link-a">
            <i class="fa fa-plus-square fa-lg fa-fw"></i>{{ 'label.tambah.layanan.sms.periodik'|trans }}
        </a>
    </li>
</ul>

<dl>
    <dt>{{ 'label.school'|trans }}</dt>
    <dd>{{ entity.sekolah.nama }}</dd>
    <dt>{{ 'label.layanansms.jenis'|trans }}</dt>
    <dd>{{ daftarJenisLayanan[entity.jenisLayanan]|trans }}</dd>
    <dt>{{ 'label.perulangan'|trans }}</dt>
    <dd>{{ daftarPerulangan[entity.perulangan] }}</dd>
    <dt>{{ 'label.day'|trans }}</dt>
    <dd>{% if entity.mingguanHariKe %}{{ daftarHari[entity.mingguanHariKe]|trans }}{% else %}&mdash;{% endif %}</dd>
    <dt>{{ 'label.monthday'|trans }}</dt>
    <dd>{% if entity.bulananHariKe %}{{ entity.bulananHariKe }}{% else %}&mdash;{% endif %}</dd>
    <dt>{{ 'label.bulan.awal'|trans }}</dt>
    <dd>{% if entity.bulanAwal %}{{ daftarBulan[entity.bulanAwal]|trans }}{% else %}&mdash;{% endif %}</dd>
    <dt>{{ 'label.kirim.sms.jam'|trans }}</dt>
    <dd>{{ entity.smsJam(false) }}</dd>
    <dt>{{ 'label.tingkat'|trans }}</dt>
    <dd>{% if entity.tingkat %}{{ entity.tingkat.optionLabel }}{% else %}∗{% endif %}</dd>
    <dt>{{ 'label.sms.template.entry'|trans }}</dt>
    <dd>{{ entity.templatesms.nama }} &raquo; {{ entity.templatesms.teks }}</dd>
    <dt>{{ 'label.active'|trans }}</dt>
    <dd>
        {% if entity.aktif == 1 %}
            <i class="fa fa-check fa-lg fa-fw check"></i>
        {% else %}
            <i class="fa fa-times fa-lg fa-fw uncheck"></i>
        {% endif %}
    </dd>
</dl>

<div class="clearfix"></div>

<form id="delete-form" action="{{ path('layanan_smsperiodik_delete', {'id': entity.id}) }}" method="post" class="form-inline pull-right">
    {{ form_widget(delete_form) }}
    <div class="form-actions">
        <button type="submit" class="btn alternative icon danger remove">{{ 'label.delete'|trans }}</button>
    </div>
</form>

<ul class="nav nav-pills">
    <li>
        <a href="{{ path('layanan_smsperiodik') }}">{{ 'link.backtolist'|trans }}</a>
    </li>
    <li>
        <a href="{{ path('layanan_smsperiodik_edit', {'id': entity.id}) }}">{{ 'link.edit'|trans }}</a>
    </li>
</ul>
{% endblock content %}

{% block javascripts_custom %}
<script language="javascript" type="text/javascript">
$(document).ready(function() {
    $("#delete-form").submit(function(){
        var confirmtext = "{{ 'confirm.drop.layanan.sms'|trans }}";
        confirmtext = confirmtext.replace(/&#039;/g, "'");
        return confirmDropButton(confirmtext);
    });
});
</script>
{% endblock javascripts_custom %}